version: "3.7"

services:
    webapp:
        build: .
        container_name: django-webmonitor-container
        volumes:
            - ./WebMonitor:/usr/src/webmonitor
        env_file: .env
        ports:
            - 8000:8000