# Generated by Django 3.2.13 on 2022-05-18 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Failure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PageName', models.TextField(default='This webpage')),
                ('StatusCode', models.TextField(default='This webpage')),
                ('FailureTimeBegin', models.DateTimeField(auto_now_add=True)),
                ('FailureTimeFixed', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='WebPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('link', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('WebPageName', models.TextField(default='Web Page')),
                ('Failures', models.ManyToManyField(blank=True, related_name='Failures', to='monitor.Failure')),
            ],
        ),
    ]
