# Generated by Django 3.2.13 on 2022-05-18 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='IsWorking',
            field=models.BooleanField(default=True),
        ),
    ]
