# Generated by Django 3.2.13 on 2022-05-21 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_alter_failure_failuretimefixed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failure',
            name='FailureTimeBegin',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
