# Generated by Django 3.2.13 on 2022-05-21 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_alter_failure_failuretimebegin'),
    ]

    operations = [
        migrations.AddField(
            model_name='failure',
            name='ResponseDataAfterFix',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='failure',
            name='ResponseDataOnFailure',
            field=models.TextField(blank=True),
        ),
    ]
