# Generated by Django 3.2.13 on 2022-05-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_webpage_isworking'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='FrequencyOfChecking',
            field=models.TextField(default='1min'),
        ),
    ]
